nome = str(input('Digite seu nome: '))
sobrenome = str(input('Digite seu sobrenome: '))
idade = int(input('Digite sua idade: '))
ano_nascimento = int(input('Digite seu ano de nascimento: '))
maior_de_idade = bool(idade >= 18)
altura_metros = float(input('Quanto de altura ?'))
print('Nome:', nome)
print('Sobrenome:', sobrenome)
print('Idade:', idade)
print('Ano de nascimento:', ano_nascimento)
print('É maior de idade ?', maior_de_idade)
print('Altura em metros:', altura_metros)